version: "3"
services:
  arch-linux-vnc:
    image: terwer/archlinux:latest
    container_name: arch-linux-vnc
    build:
      context: ./arch-linux-vnc
      dockerfile: Dockerfile
    ports:
      - "5901:5901"
    tty: true
    stdin_open: true
    volumes:
      - ./arch-linux-vnc/app:/app
      - ./arch-linux-vnc/workspace:/workspace
      - ./arch-linux-vnc/scripts:/scripts
      - ./arch-linux-vnc/config:/config
      - ./arch-linux-vnc/mytemp:/mytemp
  portable-mysql57:
    stdin_open: true
    tty: true
    image: terwer/mysql57-arch:5.7.38
    container_name: portable-mysql57-arch
    build:
     context: ./portable-mysql57-arch
     dockerfile: Dockerfile
    ports:
     - "3306:3306"
    environment:
     # 最好使用此设定时区，其它镜像也可以使用，也可以用"TZ=Asia/Shanghai"
     - "TZ=CST-8"
     - "MYSQL_ROOT_PASSWORD=123456"
     - "MYSQL_ROOT_HOST=%"
     - "MYSQL_DATABASE=test"
     - "MYSQL_USER=terwer"
     - "MYSQL_PASSWORD=123456"
    volumes:
     - ./portable-mysql57-arch/data:/var/lib/mysql
     - ./portable-mysql57-arch/init:/docker-entrypoint-initdb.d/
     - ./portable-mysql57-arch/sql:/opt/
     - ./portable-mysql57-arch/mylog:/mylog/
    restart: "no"
  portable-redis7:
    image: terwer/redis7-arch:7.0.0
    container_name: portable-redis7-arch
    build:
     context: ./portable-redis7-arch
     dockerfile: Dockerfile
    ports:
     - "6379:6379"
    environment:
     # 最好使用此设定时区，其它镜像也可以使用，也可以用"TZ=Asia/Shanghai"
     - "TZ=CST-8"
    stdin_open: true
    tty: true
    restart: "no"